sources:
  -
    SourceName: gnomad
    VersionName: gnomad.v2
    VersionId: "2019_04_19"
  -
    SourceName: ald
    VersionName: ald.v1
    VersionId: "2018_07_26"
  -
    SourceName: clinvar
    VersionName: clinvar.v1
    VersionId: "2018_07_01"
  -
    SourceName: dbsnp
    VersionName: dbsnp.v1
    VersionId: "2018_04_23"
  -
    SourceName: exac
    VersionName: exac.v2
    VersionId: "2019_05_23"
  -
    SourceName: emv
    VersionName: emv.v1
    VersionId: "2019_05_06"
  -
    SourceName: polyphen
    VersionName: polyphen.v1
    VersionId: "2019_05_07"
  -
    SourceName: pompe
    VersionName: pompe.v1
    VersionId: "2019_05_28"
  -
    SourceName: mps1
    VersionName: mps1.v1
    VersionId: "2019_06_03"
  -
    SourceName: sift
    VersionName: sift.v1
    VersionId: "2019_06_17"
